apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding  # The name of the RoleBinding
  namespace: webapps     # The namespace in which this RoleBinding applies
roleRef:
  apiGroup: rbac.authorization.k8s.io  # The API group for Role/ClusterRole
  kind: Role                           # Referring to a Role (could also be ClusterRole)
  name: app-role                       # The name of the Role to bind to
subjects:
  - kind: ServiceAccount               # The type of subject (in this case, ServiceAccount)
    name: jenkins                      # The ServiceAccount that gets the permissions
    namespace: webapps                 # The namespace of the ServiceAccount
